# Generated by Django 4.1 on 2023-05-16 20:09

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="date added"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField()),
                ("description", models.CharField(max_length=128)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("NEW", "New"),
                            ("SALE", "Sale"),
                            ("BEST_SELLER", "Best Seller"),
                        ],
                        default="NEW",
                        max_length=32,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.category_image_path
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("discount_price", models.PositiveIntegerField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField()),
                ("TNA", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        default=core.models.Category.get_default_pk,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        related_query_name="product",
                        to="core.category",
                    ),
                ),
            ],
        ),
    ]
