# Generated by Django 4.1 on 2023-05-16 20:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("text", models.CharField(max_length=128)),
                ("link", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to=core.models.carousel_image_path)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
