# Generated by Django 4.1 on 2023-05-16 21:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_carousel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.product_image_path
            ),
        ),
    ]
