# Generated by Django 4.1 on 2023-05-17 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_addedproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="addedproduct",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 17, 4, 20, 22, 830700, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date added",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addedproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
    ]
