# Generated by Django 4.1 on 2023-05-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_addedproduct_created_at_addedproduct_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addedproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("WISH_LIST", "Wish List"),
                    ("ORDERED", "Ordered"),
                    ("SHIPPED", "Shipped"),
                ],
                default="WISH_LIST",
                max_length=64,
            ),
        ),
    ]
