# Generated by Django 4.1 on 2023-05-17 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_alter_addedproduct_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acquisitions",
                related_query_name="acquisition",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="addedproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
