# Generated by Django 3.2.5 on 2023-03-11 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDirectory',
            fields=[
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Phone number already exists in directory'}, max_length=128, primary_key=True, region=None, serialize=False, verbose_name='phone')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('reporter_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spams_reported', to=settings.AUTH_USER_MODEL)),
                ('target_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spam_reports', to='core.phonedirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.phonedirectory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', related_query_name='contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('user', 'phone', 'name'), name='unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('name', None)), fields=('user', 'phone'), name='unique_without_optional'),
        ),
    ]
