# Generated by Django 3.2.5 on 2023-03-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spamdata',
            constraint=models.UniqueConstraint(fields=('target_phone', 'reporter_phone', 'name'), name='spam_unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='spamdata',
            constraint=models.UniqueConstraint(condition=models.Q(('name', None)), fields=('target_phone', 'reporter_phone'), name='spam_unique_without_optional'),
        ),
    ]
