# Generated by Django 3.2.5 on 2023-03-11 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20230312_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedirectory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_dir', to=settings.AUTH_USER_MODEL),
        ),
    ]
